#!/bin/bash

TIME=5

DIR="$( cd "$( dirname "$0" )" && pwd )"
cd $DIR
#cd pox

while [ 1 ] ; do
  ./pox.py eecore
  echo
  echo "Restarting POX in $TIME seconds.  Hit Ctrl-C to abort."
  sleep $TIME
  echo
done
